# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-31 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180729_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
